/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ISlam
 */
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
public class MFrame extends javax.swing.JFrame {

        String Ltxt1,Ltxt2;
        int Lunit1=0, Lunit2=0;
        double Lnum1,Lnum2,Lnum3;
        String Mtxt1,Mtxt2;
        int Munit1=0, Munit2=0;
        double Mnum1,Mnum2,Mnum3;
        String Ttxt1,Ttxt2;
        int Tunit1=0, Tunit2=0;
        double Tnum1,Tnum2,Tnum3;
    public MFrame() {
        
        initComponents();
        getContentPane().setBackground(new java.awt.Color(51, 51, 51));
        TB.setBackground(new java.awt.Color(51, 51, 51));
        MB.setBackground(new java.awt.Color(51, 51, 51));
        LB.setBackground(new java.awt.Color(51, 51, 51));
        Lcon.setBackground(new java.awt.Color(22, 22, 22));
        Mcon.setBackground(new java.awt.Color(22, 22, 22));
        Tcon.setBackground(new java.awt.Color(22, 22, 22));
        LTB.setBackground(new java.awt.Color(22, 22, 22));
        LMB.setBackground(new java.awt.Color(22, 22, 22));
        MLB.setBackground(new java.awt.Color(22, 22, 22));
        MTB.setBackground(new java.awt.Color(22, 22, 22));
        TMB.setBackground(new java.awt.Color(22, 22, 22));
        TLB.setBackground(new java.awt.Color(22, 22, 22));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MPan = new javax.swing.JPanel();
        start = new javax.swing.JPanel();
        LB = new javax.swing.JButton();
        MB = new javax.swing.JButton();
        TB = new javax.swing.JButton();
        P1 = new javax.swing.JPanel();
        U1 = new javax.swing.JComboBox<>();
        display1 = new javax.swing.JTextField();
        U2 = new javax.swing.JComboBox<>();
        display2 = new javax.swing.JTextField();
        err = new javax.swing.JTextField();
        Lcon = new javax.swing.JButton();
        LMB = new javax.swing.JButton();
        LTB = new javax.swing.JButton();
        P2 = new javax.swing.JPanel();
        U3 = new javax.swing.JComboBox<>();
        display3 = new javax.swing.JTextField();
        U4 = new javax.swing.JComboBox<>();
        display4 = new javax.swing.JTextField();
        err1 = new javax.swing.JTextField();
        Mcon = new javax.swing.JButton();
        MLB = new javax.swing.JButton();
        MTB = new javax.swing.JButton();
        P3 = new javax.swing.JPanel();
        U5 = new javax.swing.JComboBox<>();
        display5 = new javax.swing.JTextField();
        U6 = new javax.swing.JComboBox<>();
        display6 = new javax.swing.JTextField();
        err2 = new javax.swing.JTextField();
        Tcon = new javax.swing.JButton();
        TLB = new javax.swing.JButton();
        TMB = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        MCon = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conventer");
        setAlwaysOnTop(isAlwaysOnTopSupported());
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("icon.png")).getImage());
        setResizable(false);

        MPan.setBackground(new java.awt.Color(30, 30, 30));
        MPan.setLayout(new java.awt.CardLayout());

        start.setBackground(new java.awt.Color(51, 51, 51));

        LB.setText("Length");
        LB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LBActionPerformed(evt);
            }
        });

        MB.setText("Mass");
        MB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBActionPerformed(evt);
            }
        });

        TB.setText("Temperature");
        TB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startLayout = new javax.swing.GroupLayout(start);
        start.setLayout(startLayout);
        startLayout.setHorizontalGroup(
            startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(LB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(MB, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(TB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        startLayout.setVerticalGroup(
            startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        MPan.add(start, "card5");

        P1.setBackground(new java.awt.Color(51, 51, 51));
        P1.setForeground(new java.awt.Color(51, 51, 51));
        P1.setFocusable(false);

        U1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meter", "Inch", "Foot", "Yard", "Mile" }));
        U1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U1ActionPerformed(evt);
            }
        });

        U2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meter", "Inch", "Foot", "Yard", "Mile" }));
        U2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U2ActionPerformed(evt);
            }
        });

        display2.setEditable(false);
        display2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display2ActionPerformed(evt);
            }
        });

        err.setEditable(false);
        err.setBackground(new java.awt.Color(51, 51, 51));
        err.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        err.setForeground(new java.awt.Color(204, 0, 0));
        err.setBorder(null);
        err.setCaretColor(new java.awt.Color(51, 51, 51));
        err.setFocusable(false);
        err.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errActionPerformed(evt);
            }
        });

        Lcon.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        Lcon.setForeground(new java.awt.Color(204, 204, 204));
        Lcon.setText("Convert");
        Lcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LconActionPerformed(evt);
            }
        });
        Lcon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LconKeyPressed(evt);
            }
        });

        LMB.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        LMB.setForeground(new java.awt.Color(204, 204, 204));
        LMB.setText("Mass");
        LMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LMBActionPerformed(evt);
            }
        });

        LTB.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        LTB.setForeground(new java.awt.Color(204, 204, 204));
        LTB.setText("Temperature");
        LTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LTBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P1Layout.createSequentialGroup()
                        .addComponent(LMB, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LTB, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P1Layout.createSequentialGroup()
                                .addComponent(display1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(U1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(P1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(err, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lcon, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(display2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(U2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(display1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(U1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(display2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(U2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lcon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(err, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LTB, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(LMB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MPan.add(P1, "P1");

        P2.setBackground(new java.awt.Color(51, 51, 51));

        U3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilogram", "Pound", "US ton", "Ounce" }));
        U3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U3ActionPerformed(evt);
            }
        });

        U4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilogram", "Pound", "US ton", "Ounce" }));
        U4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U4ActionPerformed(evt);
            }
        });

        display4.setEditable(false);
        display4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display4ActionPerformed(evt);
            }
        });

        err1.setEditable(false);
        err1.setBackground(new java.awt.Color(51, 51, 51));
        err1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        err1.setForeground(new java.awt.Color(204, 0, 0));
        err1.setBorder(null);
        err1.setCaretColor(new java.awt.Color(51, 51, 51));
        err1.setFocusable(false);
        err1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                err1ActionPerformed(evt);
            }
        });

        Mcon.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        Mcon.setForeground(new java.awt.Color(204, 204, 204));
        Mcon.setText("Convert");
        Mcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MconActionPerformed(evt);
            }
        });
        Mcon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MconKeyPressed(evt);
            }
        });

        MLB.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        MLB.setForeground(new java.awt.Color(204, 204, 204));
        MLB.setText("Length");
        MLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLBActionPerformed(evt);
            }
        });

        MTB.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        MTB.setForeground(new java.awt.Color(204, 204, 204));
        MTB.setText("Temperature");
        MTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MTBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P2Layout = new javax.swing.GroupLayout(P2);
        P2.setLayout(P2Layout);
        P2Layout.setHorizontalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P2Layout.createSequentialGroup()
                        .addComponent(MLB, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MTB, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P2Layout.createSequentialGroup()
                        .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P2Layout.createSequentialGroup()
                                .addComponent(display3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(U3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(P2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(err1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Mcon, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(display4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(U4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P2Layout.setVerticalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(display3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(U3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(display4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(U4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(err1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MTB, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(MLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MPan.add(P2, "P2");

        P3.setBackground(new java.awt.Color(51, 51, 51));

        U5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Celsius", "Kelvin" }));
        U5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U5ActionPerformed(evt);
            }
        });

        U6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Celsius", "Kelvin" }));
        U6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U6ActionPerformed(evt);
            }
        });

        display6.setEditable(false);
        display6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display6ActionPerformed(evt);
            }
        });

        err2.setEditable(false);
        err2.setBackground(new java.awt.Color(51, 51, 51));
        err2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        err2.setForeground(new java.awt.Color(204, 0, 0));
        err2.setBorder(null);
        err2.setCaretColor(new java.awt.Color(51, 51, 51));
        err2.setFocusable(false);
        err2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                err2ActionPerformed(evt);
            }
        });

        Tcon.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        Tcon.setForeground(new java.awt.Color(204, 204, 204));
        Tcon.setText("Convert");
        Tcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TconActionPerformed(evt);
            }
        });
        Tcon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TconKeyPressed(evt);
            }
        });

        TLB.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        TLB.setForeground(new java.awt.Color(204, 204, 204));
        TLB.setText("Length");
        TLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TLBActionPerformed(evt);
            }
        });

        TMB.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        TMB.setForeground(new java.awt.Color(204, 204, 204));
        TMB.setText("Mass");
        TMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TMBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P3Layout = new javax.swing.GroupLayout(P3);
        P3.setLayout(P3Layout);
        P3Layout.setHorizontalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(err2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(P3Layout.createSequentialGroup()
                                .addComponent(display5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(U5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tcon, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(display6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(U6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(TLB, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TMB, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P3Layout.setVerticalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(display5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(U5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(display6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(U6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tcon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(err2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TMB, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(TLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MPan.add(P3, "P3");

        MCon.setText("File");
        MCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LconActionPerformed(evt);
            }
        });

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        MCon.add(Exit);

        Menu.add(MCon);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(MPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MPan, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBActionPerformed
         CardLayout card = (CardLayout)MPan.getLayout();
         card.show(MPan, "P3");
         
    }//GEN-LAST:event_TBActionPerformed

    private void LBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LBActionPerformed
         CardLayout card = (CardLayout)MPan.getLayout();
    card.show(MPan, "P1");
    LB.setVisible(false);
    
    }//GEN-LAST:event_LBActionPerformed

    private void MBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBActionPerformed
         CardLayout card = (CardLayout)MPan.getLayout();
    card.show(MPan, "P2");
    }//GEN-LAST:event_MBActionPerformed

    private void LconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LconActionPerformed
          
        Ltxt1=display1.getText();
       try {  
                 Lnum1 = Double.parseDouble(Ltxt1);
                 err.setText("") ;  
        }catch(NumberFormatException ex){  
           err.setText("  not a number.") ;
        }
       if(Lunit1==4&&Lunit2==4)
       {  if(Lnum1==(int)Lnum1)
            display2.setText(Integer.toString((int)Lnum1));
       else
            display2.setText(Double.toString(Lnum1));}
       else
       {
       switch(Lunit1){
             case 0:
                Lnum2=Lnum1;
                break;
             case 1:
                Lnum2=0.0254*Lnum1;
                break;
             case 2:
                Lnum2=0.3048*Lnum1;
                break;
             case 3:
                Lnum2=0.9144*Lnum1;
                break;
             case 4:
                 Lnum2=1609.34*Lnum1;
                 break;
                }
        switch(Lunit2){
             case 0:
                Lnum3=Lnum2;
                break;
             case 1:
                Lnum3=39.3701*Lnum2;
                break;
             case 2:
                Lnum3=3.280841666667*Lnum2;
                break;
             case 3:
                Lnum3=1.0936138888889999077*Lnum2;
                break;
             case 4:
                 Lnum3=0.000621371*Lnum2;
                 break;
                }
       Lnum3 = Math.floor(Lnum3 * 10000) / 10000;
       if(Lnum3==(int)Lnum3)
            display2.setText(Integer.toString((int)Lnum3));
       else
            display2.setText(Double.toString(Lnum3));
                    
       }
    }//GEN-LAST:event_LconActionPerformed

    private void U1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U1ActionPerformed
          Lunit1=U1.getSelectedIndex();
    }//GEN-LAST:event_U1ActionPerformed

    private void U2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U2ActionPerformed
         Lunit2=U2.getSelectedIndex();
    }//GEN-LAST:event_U2ActionPerformed

    private void LconKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LconKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
     
   }
    }//GEN-LAST:event_LconKeyPressed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void display2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_display2ActionPerformed

    private void errActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errActionPerformed

    private void LMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LMBActionPerformed
         CardLayout card = (CardLayout)MPan.getLayout();
    card.show(MPan, "P2");
    }//GEN-LAST:event_LMBActionPerformed

    private void LTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LTBActionPerformed
         CardLayout card = (CardLayout)MPan.getLayout();
    card.show(MPan, "P3");
    }//GEN-LAST:event_LTBActionPerformed

    private void U3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U3ActionPerformed
         Munit1=U3.getSelectedIndex();
    }//GEN-LAST:event_U3ActionPerformed

    private void U4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U4ActionPerformed
         Munit2=U4.getSelectedIndex();
    }//GEN-LAST:event_U4ActionPerformed

    private void display4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_display4ActionPerformed

    private void err1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_err1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_err1ActionPerformed

    private void MconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MconActionPerformed
         Mtxt1=display3.getText();
       try {  
                 Mnum1 = Double.parseDouble(Mtxt1);
                 err1.setText("") ;  
        }catch(NumberFormatException ex){  
           err1.setText("  not a number.") ;
        }
       switch(Munit1){
             case 0:
                Mnum2=Mnum1;
                break;
             case 2:
                Mnum2=907.185*Mnum1;
                break;
             case 1:
                Mnum2=0.45359250018101*Mnum1;
                break;
             case 3:
                Mnum2=0.028349531261313124647*Mnum1;
                break;
                }
        switch(Munit2){
             case 0:
                Mnum3=Mnum2;
                break;
             case 2:
                Mnum3=0.0011023116272877336082*Mnum2;
                break;
             case 1:
               Mnum3=2.2046232545754671506*Mnum2;
                break;
             case 3:
                Mnum3=35.273972073207474409*Mnum2;
                break;
                }
       Mnum3 = Math.floor(Mnum3 * 10000) / 10000;
       if(Mnum3==(int)Mnum3)
            display4.setText(Integer.toString((int)Mnum3));
       else
            display4.setText(Double.toString(Mnum3));
    }//GEN-LAST:event_MconActionPerformed

    private void MconKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MconKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MconKeyPressed

    private void MLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLBActionPerformed
        CardLayout card = (CardLayout)MPan.getLayout();
    card.show(MPan, "P1");
    }//GEN-LAST:event_MLBActionPerformed

    private void MTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MTBActionPerformed
        CardLayout card = (CardLayout)MPan.getLayout();
    card.show(MPan, "P3");
    }//GEN-LAST:event_MTBActionPerformed

    private void U5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U5ActionPerformed
           Tunit1=U5.getSelectedIndex();
    }//GEN-LAST:event_U5ActionPerformed

    private void U6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U6ActionPerformed
           Tunit2=U6.getSelectedIndex();
    }//GEN-LAST:event_U6ActionPerformed

    private void display6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_display6ActionPerformed

    private void err2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_err2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_err2ActionPerformed

    private void TconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TconActionPerformed
         Ttxt1=display5.getText();
       try {  
                 Tnum1 = Double.parseDouble(Ttxt1);
                 err2.setText("") ;  
        }
       catch(NumberFormatException ex){  
           err2.setText("  not a number.") ;
       } 
           
       switch(Tunit1){
             case 0:
                Tnum2=Tnum1;
                break;
             case 1:
                Tnum2=(Tnum1*9/5.0)+32;
                break;
             case 2:
                Tnum2=(Tnum1-273.15)*9/5.0+32;
                break;
                }
        switch(Tunit2){
             case 0:
                Tnum3=Tnum2;
                break;
             case 1:
                Tnum3=(Tnum2-32)*5/9.0;
                break;
             case 2:
                Tnum3=(Tnum2-32)*5/9.0+273.15;
                break;
                }
       Tnum3 = Math.floor(Tnum3 * 10000) / 10000;
       if(Tnum3==(int)Tnum3)
            display6.setText(Integer.toString((int)Tnum3));
       else
            display6.setText(Double.toString(Tnum3));
                    
       
    }//GEN-LAST:event_TconActionPerformed

    private void TconKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TconKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TconKeyPressed

    private void TLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TLBActionPerformed
     CardLayout card = (CardLayout)MPan.getLayout();
    card.show(MPan, "P1");
    }//GEN-LAST:event_TLBActionPerformed

    private void TMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TMBActionPerformed
       CardLayout card = (CardLayout)MPan.getLayout();
    card.show(MPan, "P2");
    }//GEN-LAST:event_TMBActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JButton LB;
    private javax.swing.JButton LMB;
    private javax.swing.JButton LTB;
    private javax.swing.JButton Lcon;
    private javax.swing.JButton MB;
    private javax.swing.JMenu MCon;
    private javax.swing.JButton MLB;
    private javax.swing.JPanel MPan;
    private javax.swing.JButton MTB;
    private javax.swing.JButton Mcon;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JPanel P1;
    private javax.swing.JPanel P2;
    private javax.swing.JPanel P3;
    private javax.swing.JButton TB;
    private javax.swing.JButton TLB;
    private javax.swing.JButton TMB;
    private javax.swing.JButton Tcon;
    private javax.swing.JComboBox<String> U1;
    private javax.swing.JComboBox<String> U2;
    private javax.swing.JComboBox<String> U3;
    private javax.swing.JComboBox<String> U4;
    private javax.swing.JComboBox<String> U5;
    private javax.swing.JComboBox<String> U6;
    private javax.swing.JTextField display1;
    private javax.swing.JTextField display2;
    private javax.swing.JTextField display3;
    private javax.swing.JTextField display4;
    private javax.swing.JTextField display5;
    private javax.swing.JTextField display6;
    private javax.swing.JTextField err;
    private javax.swing.JTextField err1;
    private javax.swing.JTextField err2;
    private javax.swing.JPanel start;
    // End of variables declaration//GEN-END:variables
}
